// Code generated for student service
// KraPaGen© Student 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/krapagen/my_microservices_rocket/iam/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewSessionRepository creates a new instance of SessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepository {
	mock := &SessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SessionRepository is an autogenerated mock type for the SessionRepository type
type SessionRepository struct {
	mock.Mock
}

type SessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionRepository) EXPECT() *SessionRepository_Expecter {
	return &SessionRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type SessionRepository
func (_mock *SessionRepository) Delete(ctx context.Context, uuid string) error {
	ret := _mock.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, uuid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type SessionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *SessionRepository_Expecter) Delete(ctx interface{}, uuid interface{}) *SessionRepository_Delete_Call {
	return &SessionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, uuid)}
}

func (_c *SessionRepository_Delete_Call) Run(run func(ctx context.Context, uuid string)) *SessionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepository_Delete_Call) Return(err error) *SessionRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, uuid string) error) *SessionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type SessionRepository
func (_mock *SessionRepository) Get(ctx context.Context, uuid string) (model.Session, error) {
	ret := _mock.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Session, error)); ok {
		return returnFunc(ctx, uuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Session); ok {
		r0 = returnFunc(ctx, uuid)
	} else {
		r0 = ret.Get(0).(model.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type SessionRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *SessionRepository_Expecter) Get(ctx interface{}, uuid interface{}) *SessionRepository_Get_Call {
	return &SessionRepository_Get_Call{Call: _e.mock.On("Get", ctx, uuid)}
}

func (_c *SessionRepository_Get_Call) Run(run func(ctx context.Context, uuid string)) *SessionRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepository_Get_Call) Return(session model.Session, err error) *SessionRepository_Get_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *SessionRepository_Get_Call) RunAndReturn(run func(ctx context.Context, uuid string) (model.Session, error)) *SessionRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type SessionRepository
func (_mock *SessionRepository) Set(ctx context.Context, uuid string, session model.Session, ttl time.Duration) error {
	ret := _mock.Called(ctx, uuid, session, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.Session, time.Duration) error); ok {
		r0 = returnFunc(ctx, uuid, session, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepository_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type SessionRepository_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - session model.Session
//   - ttl time.Duration
func (_e *SessionRepository_Expecter) Set(ctx interface{}, uuid interface{}, session interface{}, ttl interface{}) *SessionRepository_Set_Call {
	return &SessionRepository_Set_Call{Call: _e.mock.On("Set", ctx, uuid, session, ttl)}
}

func (_c *SessionRepository_Set_Call) Run(run func(ctx context.Context, uuid string, session model.Session, ttl time.Duration)) *SessionRepository_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.Session
		if args[2] != nil {
			arg2 = args[2].(model.Session)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *SessionRepository_Set_Call) Return(err error) *SessionRepository_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepository_Set_Call) RunAndReturn(run func(ctx context.Context, uuid string, session model.Session, ttl time.Duration) error) *SessionRepository_Set_Call {
	_c.Call.Return(run)
	return _c
}
