// Code generated for student service
// KraPaGen© Student 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/krapagen/my_microservices_rocket/iam/internal/model"
	"github.com/krapagen/my_microservices_rocket/iam/internal/service/input"
	mock "github.com/stretchr/testify/mock"
)

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// GetUser provides a mock function for the type Service
func (_mock *Service) GetUser(ctx context.Context, userUUID uuid.UUID) (model.User, error) {
	ret := _mock.Called(ctx, userUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.User, error)); ok {
		return returnFunc(ctx, userUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.User); ok {
		r0 = returnFunc(ctx, userUUID)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type Service_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID uuid.UUID
func (_e *Service_Expecter) GetUser(ctx interface{}, userUUID interface{}) *Service_GetUser_Call {
	return &Service_GetUser_Call{Call: _e.mock.On("GetUser", ctx, userUUID)}
}

func (_c *Service_GetUser_Call) Run(run func(ctx context.Context, userUUID uuid.UUID)) *Service_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_GetUser_Call) Return(user model.User, err error) *Service_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *Service_GetUser_Call) RunAndReturn(run func(ctx context.Context, userUUID uuid.UUID) (model.User, error)) *Service_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type Service
func (_mock *Service) Login(ctx context.Context, input1 input.LoginInput) (uuid.UUID, error) {
	ret := _mock.Called(ctx, input1)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.LoginInput) (uuid.UUID, error)); ok {
		return returnFunc(ctx, input1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.LoginInput) uuid.UUID); ok {
		r0 = returnFunc(ctx, input1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, input.LoginInput) error); ok {
		r1 = returnFunc(ctx, input1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type Service_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - input1 input.LoginInput
func (_e *Service_Expecter) Login(ctx interface{}, input1 interface{}) *Service_Login_Call {
	return &Service_Login_Call{Call: _e.mock.On("Login", ctx, input1)}
}

func (_c *Service_Login_Call) Run(run func(ctx context.Context, input1 input.LoginInput)) *Service_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 input.LoginInput
		if args[1] != nil {
			arg1 = args[1].(input.LoginInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_Login_Call) Return(uUID uuid.UUID, err error) *Service_Login_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *Service_Login_Call) RunAndReturn(run func(ctx context.Context, input1 input.LoginInput) (uuid.UUID, error)) *Service_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type Service
func (_mock *Service) Logout(ctx context.Context, session uuid.UUID) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type Service_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - session uuid.UUID
func (_e *Service_Expecter) Logout(ctx interface{}, session interface{}) *Service_Logout_Call {
	return &Service_Logout_Call{Call: _e.mock.On("Logout", ctx, session)}
}

func (_c *Service_Logout_Call) Run(run func(ctx context.Context, session uuid.UUID)) *Service_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_Logout_Call) Return(err error) *Service_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_Logout_Call) RunAndReturn(run func(ctx context.Context, session uuid.UUID) error) *Service_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type Service
func (_mock *Service) Register(ctx context.Context, input1 input.RegisterInput) (uuid.UUID, error) {
	ret := _mock.Called(ctx, input1)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.RegisterInput) (uuid.UUID, error)); ok {
		return returnFunc(ctx, input1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.RegisterInput) uuid.UUID); ok {
		r0 = returnFunc(ctx, input1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, input.RegisterInput) error); ok {
		r1 = returnFunc(ctx, input1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type Service_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - input1 input.RegisterInput
func (_e *Service_Expecter) Register(ctx interface{}, input1 interface{}) *Service_Register_Call {
	return &Service_Register_Call{Call: _e.mock.On("Register", ctx, input1)}
}

func (_c *Service_Register_Call) Run(run func(ctx context.Context, input1 input.RegisterInput)) *Service_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 input.RegisterInput
		if args[1] != nil {
			arg1 = args[1].(input.RegisterInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_Register_Call) Return(uUID uuid.UUID, err error) *Service_Register_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *Service_Register_Call) RunAndReturn(run func(ctx context.Context, input1 input.RegisterInput) (uuid.UUID, error)) *Service_Register_Call {
	_c.Call.Return(run)
	return _c
}

// WhoAmI provides a mock function for the type Service
func (_mock *Service) WhoAmI(ctx context.Context, sessionUuid uuid.UUID) (model.Session, model.User, error) {
	ret := _mock.Called(ctx, sessionUuid)

	if len(ret) == 0 {
		panic("no return value specified for WhoAmI")
	}

	var r0 model.Session
	var r1 model.User
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Session, model.User, error)); ok {
		return returnFunc(ctx, sessionUuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Session); ok {
		r0 = returnFunc(ctx, sessionUuid)
	} else {
		r0 = ret.Get(0).(model.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) model.User); ok {
		r1 = returnFunc(ctx, sessionUuid)
	} else {
		r1 = ret.Get(1).(model.User)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = returnFunc(ctx, sessionUuid)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Service_WhoAmI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WhoAmI'
type Service_WhoAmI_Call struct {
	*mock.Call
}

// WhoAmI is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionUuid uuid.UUID
func (_e *Service_Expecter) WhoAmI(ctx interface{}, sessionUuid interface{}) *Service_WhoAmI_Call {
	return &Service_WhoAmI_Call{Call: _e.mock.On("WhoAmI", ctx, sessionUuid)}
}

func (_c *Service_WhoAmI_Call) Run(run func(ctx context.Context, sessionUuid uuid.UUID)) *Service_WhoAmI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_WhoAmI_Call) Return(session model.Session, user model.User, err error) *Service_WhoAmI_Call {
	_c.Call.Return(session, user, err)
	return _c
}

func (_c *Service_WhoAmI_Call) RunAndReturn(run func(ctx context.Context, sessionUuid uuid.UUID) (model.Session, model.User, error)) *Service_WhoAmI_Call {
	_c.Call.Return(run)
	return _c
}
